# Generated by Django 4.0 on 2024-07-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_userquizsession_current_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizsession',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userquizsession',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
