# Generated by Django 4.0 on 2024-07-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_userquizsession_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestionsoptions',
            name='correct_option',
            field=models.BooleanField(default=False),
        ),
    ]
