# Generated by Django 4.0 on 2024-08-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_essaygrade_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaygrade',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
