# Generated by Django 4.0 on 2024-07-29 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0007_alter_multiplechoicequestionsoptions_correct_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('grader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essay_grader', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('answers', models.JSONField(default=dict)),
                ('score_calculated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit in minutes', null=True),
        ),
        migrations.DeleteModel(
            name='UserQuizSession',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='essaygrade',
            name='quiz_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_grades', to='quiz.quizattempt'),
        ),
        migrations.AddField(
            model_name='essaygrade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essay_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='essaygrade',
            unique_together={('quiz_attempt', 'question')},
        ),
    ]
