# Generated by Django 4.0 on 2024-07-05 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_categories_delete_userlearningpath'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseactivity',
            old_name='course',
            new_name='activity_course',
        ),
        migrations.RenameField(
            model_name='lessonactivity',
            old_name='lesson',
            new_name='activity_lesson',
        ),
        migrations.RenameField(
            model_name='moduleactivity',
            old_name='module',
            new_name='activity_module',
        ),
        migrations.AlterUniqueTogether(
            name='courseactivity',
            unique_together={('activity_course', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonactivity',
            unique_together={('activity_lesson', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleactivity',
            unique_together={('activity_module', 'created_by')},
        ),
    ]
